parse-server:
  #build: .
  image: kibukamusoke/parse-server
  ports:
    - "8084:8081"
  environment:
    PORT: 8081
    USE_SSL: "true"
    SSL_SERVER_CERT_FILE: "server.crt"
    SSL_SERVER_KEY_FILE: "server.key"
    DATABASE_URI: "mongodb://172.17.0.1:27020/appdata"
    POSTGRES_URL: "postgresql://postgres:postgres@172.17.0.1:5433/ezpoint"
    APP_ID: "app11"
    MASTER_KEY: "app11!@#123"
    PARSE_MOUNT: "/parse"
    REST_API_KEY: "app11!@#123"
    JAVASCRIPT_KEY: "app11!@#123"
    FACEBOOK_APP_IDS: "unknown"
    SERVER_URL: "http://ezpoint.ezeemoney.biz:8084"
    FIREBASE_SENDER_ID: "209761675560"
    FIREBASE_API_KEY: "AAAAMNbFKSg:APA91bFL96uVjECqo94da8NdBAEYLmNKSCELMLHF7--NlqJAbKQ0mTrr_1z9I61mrKTbkCiRfwWO5vqoBFlDh80QBu1E1m8jTeQlV8c9MvZafwWNf5rz0qqKCFwmb3MXEFfmIlCue0tU"
    IOS_BUNDLE_ID: "my.tracksol.notify"
    VERIFY_USER_EMAILS: 0
    EMAIL_MODULE: "" # "" or "parse-server-simple-mailgun-adapter"
    EMAIL_FROM: ""
    EMAIL_DOMAIN: ""
    EMAIL_API_KEY: ""
    EMAIL_DISPLAY_NAME: ""
    EMAIL_REPLY_TO: ""
    EMAIL_VERIFICATION_SUBJECT: ""
    EMAIL_VERIFICATION_BODY: ""
    EMAIL_PASSWORD_RESET_SUBJECT: ""
    EMAIL_PASSWORD_RESET_BODY: ""

    PRODUCTION: "true" #production mode true or false

    ADMINUSERNAME: "admin"
    ADMINPASSWORD: "Money123"

    APP_NAME: "Notify"
    S3_ACCESS_KEY:    ""
    S3_SECRET_KEY:    ""
    S3_BUCKET:        ""
    S3_DIRECT:        ""
    GCP_PROJECT_ID:   ""
    GCP_KEYFILE_PATH: ""
    GCS_BUCKET:       ""
    GCS_DIRECT:       "false"
    AZURE_ACCOUNT:    ""
    AZURE_CONTAINER:  ""
    AZURE_ACCESS_KEY: ""
    AZURE_DIRECT:     ""
    LIVEQUERY_CLASSES: "Message"
    GRAPHQL_SUPPORT:  "0"
    GRAPHQL_SCHEMA:   ""
    LOG_LEVEL:        ""
  links:
    - mongo
    - PostgreSQL
  volumes:
    - ./cloud-code:/usr/src/app/cloud
    - ./cloud-files:/usr/src/app/files
mongo:
  image: mongo:3.0.8 # ref. https://github.com/ParsePlatform/parse-server/issues/1913
  ports:
    - "27020:27017"
  volumes_from:
    - mongo-data
  environment:
    MONGODB_USER: "admin"
    MONGODB_DATABASE: "appdata"
    MONGODB_PASS: "admin123"

#  command: "--smallfiles --logpath=/dev/null --setParameter failIndexKeyTooLong=false --rest --auth"
  command: "--smallfiles --logpath=/dev/null --setParameter failIndexKeyTooLong=false"
# ref. http://www.diogogmt.com/running-mongodb-with-docker-and-compose/

mongo-data:
  image: mongo
  volumes:
    - ./db-data:/data/db
  command: "--break-mongo"


PostgreSQL:
  restart: always
  image: kibukamusoke/postgresql:9.6-2
  ports:
    - "5433:5432"
  environment:
    - DEBUG=false
    - PG_TRUST_LOCALNET=true
    - PG_PASSWORD=passw0rd

    - DB_USER=postgres
    - DB_PASS=postgres
    - DB_NAME=ezpoint
    - DB_TEMPLATE=template1

    - DB_EXTENSION=plpythonu

    - REPLICATION_MODE=master
    - REPLICATION_USER=repluser
    - REPLICATION_PASS=repluserPass
    - REPLICATION_SSLMODE=prefer
  volumes:
    - ./postgresql:/var/lib/postgresql


# vim:set et ts=2 sw=2: